name: Build Multi-Arch Docker Image

on:
  push:
    branches:
    - "7.17"
  pull_request:
    branches: []

# permissions are needed if pushing to ghcr.io
# permissions: 
#   packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm64,linux/amd64 --push -t cameronkerrnz/logstash-plugin-dev:${{ github.ref_name }} .

    # Get the repository's code
    - name: Checkout
      uses: actions/checkout@v3

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    # - name: Login to GHCR
    #   if: github.event_name != 'pull_request'
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/docker/login-action
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Container image tag generation
      id: image_tagging # you'll use this in the next step
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          cameronkerrnz/logstash-plugin-dev
        # Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.image_tagging.outputs.tags }}
        labels: ${{ steps.image_tagging.outputs.labels }}
